### ISSUE TITLE
[FEATURE] Tidal allow downloading favourites

### ISSUE THREAD

**Issue by ChrisOboe** [nathom/streamrip#404]
### Is the feature request related to a problem. Please describe it.

I have a lot os albums, artists, etc. marked as favourite in tidal. they appear under this url: https://listen.tidal.com/my-collection/albums

I'd like to download all of them at once. I tried `rip url https://listen.tidal.com/my-collection/albums`
but that only led to this error:

```
Logged into Tidal

  AssertionError



  at /nix/store/v50nx70g6jx0wwcmjv9lafrpfc0fkf6x-python3.10-streamrip-1.9.7/lib/python3.10/site-packages/rip/core.py:201 in handle_item
      197│         if media_type not in MEDIA_TYPES:
      198│             if "playlist" in media_type:  # for SoundCloud
      199│                 media_type = "playlist"
      200│
    → 201│         assert media_type in MEDIA_TYPES, media_type
      202│         item = MEDIA_CLASS[media_type](client=client, id=item_id)
      203│         self.append(item)
      204│
      205│     def _get_download_args(self) -> dict:

If this was unexpected, please open a Bug Report at https://github.com/nathom/streamrip/issues/new/choose
```

### Describe the solution you would like.

Add a feature to support these my-colletion type of urls. 

### Describe alternatives you've considered.

I'm writing a script that parses streamrips config file to get the bearer token needed for doing api requests, calling the api of getting the favourites, parsing it und calling streamrip. This works but it would be great if this feature would be integrated in streamrip

If someone wants to use the same workarround; here is the script:
```
#!/usr/bin/env bash

TOKEN=$(grep "access_token = " ~/.config/streamrip/config.toml | cut -d = -f 2 | tr -d \")
FAVOURITES=$(curl -H "Authorization: Bearer ${TOKEN}" "https://listen.tidal.com/v1/users/50436205/favorites/ids?countryCode=DE&locale=en_US&deviceType=BROWSER")
ARTISTS=$(echo $FAVOURITES | jq '.ARTIST[]' -r)
ALBUMS=$(echo $FAVOURITES | jq '.ALBUM[]' -r)

for ARTIST in $ARTISTS; do
        rip url "https://listen.tidal.com/artist/${ARTIST}"
done

for ALBUM in $ALBUMS; do
        rip url "https://listen.tidal.com/album/${ALBUM}"
done
```

**Comment by ChrisOboe** [comment]
Here is an example of the relevant api call needed to construct all the other urls needed for downloading: `https://listen.tidal.com/v1/users/50436205/favorites/ids?countryCode=DE&locale=en_US&deviceType=BROWSER`

**Comment by fuzxi** [comment]
Hi Chris, thank you so much for posting your script. I've been meaning to put together something like that for a while and never quite got around to it. I've made a couple of improvements, so I'll post my version here in case you or anyone else is interested.

```
#!/usr/bin/env bash

CONFIG=~/.config/streamrip/config.toml

TOKEN=$(grep "access_token = " ${CONFIG} | cut -d = -f 2 | tr -d \")
ID=$(grep "user_id = " ${CONFIG} | cut -d = -f 2 | tr -d [:space:])
COUNTRY=$(grep "country_code = " ${CONFIG} | cut -d = -f 2 | tr -d \" | tr -d [:space:])
FAVOURITES=$(curl -H "Authorization: Bearer ${TOKEN}" "https://listen.tidal.com/v1/users/${ID}/favorites/ids?countryCode=${COUNTRY}&locale=en_US&deviceType=BROWSER")
ARTISTS=($(echo $FAVOURITES | jq '.ARTIST[]' -r))
ALBUMS=($(echo $FAVOURITES | jq '.ALBUM[]' -r))
TRACKS=($(echo $FAVOURITES | jq '.TRACK[]' -r))
PLAYLISTS=($(echo $FAVOURITES | jq '.PLAYLIST[]' -r))

ARTISTS=("${ARTISTS[@]/#/https://listen.tidal.com/artist/}")
ALBUMS=("${ALBUMS[@]/#/https://listen.tidal.com/album/}")
TRACKS=("${TRACKS[@]/#/https://listen.tidal.com/track/}")
PLAYLISTS=("${PLAYLISTS[@]/#/https://listen.tidal.com/playlist/}")

rip url "${ARTISTS[*]}"
rip url "${ALBUMS[*]}"
rip url "${TRACKS[*]}"
rip url "${PLAYLISTS[*]}"
```

This version reads user ID and country directly from the config file, adds track + playlist support, and stores media URLs in an array instead of a variable, essentially running `rip url $URL1 $URL2 ...` instead of `rip url $URL1 && rip url $URL2 ...`. This doesn't enable concurrent downloads when it wasn't available before (i.e. downloading favourited single tracks), but checking for already-downloaded items is sped up significantly (checking a library of 200 downloaded songs takes ~3 minutes with the variable method and ~2 seconds with the array method). 
Also note that playlists are a little wonky when used with the downloads database. Streamrip only stores the playlist's ID, which never changes, so it will always consider a downloaded playlist to be already-downloaded even if it there are new tracks added to it.

Hope someone finds this useful!

**Comment by isle9** [comment]
> This doesn't enable concurrent downloads when it wasn't available before (i.e. downloading favourited single tracks), but checking for already-downloaded items is sped up significantly (checking a library of 200 downloaded songs takes ~3 minutes with the variable method and ~2 seconds with the array method).

How fast would this script be for download 10k favorited tracks?

**Comment by Seb3thehacker** [comment]
How could this be implemented?
