### ISSUE TITLE
[FEATURE] <Streamrip>

### ISSUE THREAD

**Issue by Mightyretro** [nathom/streamrip#521]
### Is the feature request related to a problem. Please describe it.

Hi,

### Describe the solution you would like.

Hi,

1. is it possible to to have like a wating queue list where you could add "https://tidal.com/browse/artist/9185" or "https://tidal.com/browse/album/138802" periodic scanning this "text file" to download the next one in the queue.

2. is it possible to make a ".appimage" streamrip.

Kind regards / Bill

**Comment by nathom** [comment]
> is it possible to to have like a wating queue list where you could add "https://tidal.com/browse/artist/9185" or "https://tidal.com/browse/album/138802" periodic scanning this "text file" to download the next one in the queue.

This would require a daemon that is constantly running streamrip, which is out of the scope of this project. You can achieve the desired functionality by writing a bash script that calls `rip file` repeatedly on the same file.

> is it possible to make a ".appimage" streamrip.

Yes, but it's not currently planned since it's pretty easy to install anywhere with pip.
