### ISSUE TITLE
UnknownB-UnknownkHz

### ISSUE THREAD

**Issue by zzzzzozzzzz** [nathom/streamrip#70]
- If `[{bit_depth}B-{sampling_rate}kHz]` is set in config file `[UnknownB-UnknownkHz]` is added to the folder path when `1` is set as audio quality. 

This issue is likely to be repeated with other configurations as well.

**Comment by nathom** [comment]
This happens with MP3 files because they don't have a meaningful bit depth or sampling rate. Unfortunately, you'll have to remove the field from the `path_format: folder:` section to fix this. 

Changing it would require a rewrite of the naming system, which I don't think is worth it for this minor issue.
